Global:
  rec_inference_model_dir: "./cartoon/model"
  batch_size: 1
  use_gpu: True
  enable_mkldnn: True
  cpu_num_threads: 100
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

RecPreProcess:
  transform_ops:
    - ResizeImage:
        resize_short: 256
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:

RecPostProcess: null

IndexProcess:
  index_path: "./cartoon/index/"
  image_root: "./cartoon/dataset/"
  data_file:  "./cartoon/data_file.txt"
  delimiter:  "\t"
  dist_type: "IP"
  pq_size: 100
  embedding_size: 2048
